/* FaceDetectorInterface.c generated by valac 0.38.4-dirty, the Vala compiler
 * generated from FaceDetectorInterface.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gee.h>


#define COM_FACEDETECT_TYPE_FACE_DETECTOR_INTERFACE (com_facedetect_face_detector_interface_get_type ())
#define COM_FACEDETECT_FACE_DETECTOR_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), COM_FACEDETECT_TYPE_FACE_DETECTOR_INTERFACE, comfacedetectFaceDetectorInterface))
#define COM_FACEDETECT_IS_FACE_DETECTOR_INTERFACE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), COM_FACEDETECT_TYPE_FACE_DETECTOR_INTERFACE))
#define COM_FACEDETECT_FACE_DETECTOR_INTERFACE_GET_INTERFACE(obj) (G_TYPE_INSTANCE_GET_INTERFACE ((obj), COM_FACEDETECT_TYPE_FACE_DETECTOR_INTERFACE, comfacedetectFaceDetectorInterfaceIface))

typedef struct _comfacedetectFaceDetectorInterface comfacedetectFaceDetectorInterface;
typedef struct _comfacedetectFaceDetectorInterfaceIface comfacedetectFaceDetectorInterfaceIface;

struct _comfacedetectFaceDetectorInterfaceIface {
	GTypeInterface parent_iface;
	GeeList* (*detectFaces) (comfacedetectFaceDetectorInterface* self);
};



GType com_facedetect_face_detector_interface_get_type (void) G_GNUC_CONST;
GeeList* com_facedetect_face_detector_interface_detectFaces (comfacedetectFaceDetectorInterface* self);


/**
        * Questo metodo dovrà contenere le logiche per il riconoscimento delle facce
        * all'interno di una foto. Restituisce una lista di Facce di tipo anonimo.
        * L'anoniminità del tipo consente di avere liste di Rettangoli, ROI ecc.
        * @return List<R> Lista di Facce riconosciute
        */
GeeList* com_facedetect_face_detector_interface_detectFaces (comfacedetectFaceDetectorInterface* self) {
	g_return_val_if_fail (self != NULL, NULL);
	return COM_FACEDETECT_FACE_DETECTOR_INTERFACE_GET_INTERFACE (self)->detectFaces (self);
}


static void com_facedetect_face_detector_interface_base_init (comfacedetectFaceDetectorInterfaceIface * iface) {
	static gboolean initialized = FALSE;
	if (!initialized) {
		initialized = TRUE;
	}
}


GType com_facedetect_face_detector_interface_get_type (void) {
	static volatile gsize com_facedetect_face_detector_interface_type_id__volatile = 0;
	if (g_once_init_enter (&com_facedetect_face_detector_interface_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (comfacedetectFaceDetectorInterfaceIface), (GBaseInitFunc) com_facedetect_face_detector_interface_base_init, (GBaseFinalizeFunc) NULL, (GClassInitFunc) NULL, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
		GType com_facedetect_face_detector_interface_type_id;
		com_facedetect_face_detector_interface_type_id = g_type_register_static (G_TYPE_INTERFACE, "comfacedetectFaceDetectorInterface", &g_define_type_info, 0);
		g_type_interface_add_prerequisite (com_facedetect_face_detector_interface_type_id, G_TYPE_OBJECT);
		g_once_init_leave (&com_facedetect_face_detector_interface_type_id__volatile, com_facedetect_face_detector_interface_type_id);
	}
	return com_facedetect_face_detector_interface_type_id__volatile;
}



