/* Imgcodecs.c generated by valac 0.38.4-dirty, the Vala compiler
 * generated from Imgcodecs.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>


#define IMGCODECS_TYPE_IMGCODECS (imgcodecs_imgcodecs_get_type ())
#define IMGCODECS_IMGCODECS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), IMGCODECS_TYPE_IMGCODECS, imgcodecsImgcodecs))
#define IMGCODECS_IMGCODECS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), IMGCODECS_TYPE_IMGCODECS, imgcodecsImgcodecsClass))
#define IMGCODECS_IS_IMGCODECS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), IMGCODECS_TYPE_IMGCODECS))
#define IMGCODECS_IS_IMGCODECS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), IMGCODECS_TYPE_IMGCODECS))
#define IMGCODECS_IMGCODECS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), IMGCODECS_TYPE_IMGCODECS, imgcodecsImgcodecsClass))

typedef struct _imgcodecsImgcodecs imgcodecsImgcodecs;
typedef struct _imgcodecsImgcodecsClass imgcodecsImgcodecsClass;
typedef struct _imgcodecsImgcodecsPrivate imgcodecsImgcodecsPrivate;
enum  {
	IMGCODECS_IMGCODECS_0_PROPERTY,
	IMGCODECS_IMGCODECS_NUM_PROPERTIES
};
static GParamSpec* imgcodecs_imgcodecs_properties[IMGCODECS_IMGCODECS_NUM_PROPERTIES];

#define GEOMETRY_TYPE_MAT (geometry_mat_get_type ())
#define GEOMETRY_MAT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_MAT, geometryMat))
#define GEOMETRY_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_MAT, geometryMatClass))
#define GEOMETRY_IS_MAT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_MAT))
#define GEOMETRY_IS_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_MAT))
#define GEOMETRY_MAT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_MAT, geometryMatClass))

typedef struct _geometryMat geometryMat;
typedef struct _geometryMatClass geometryMatClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _imgcodecsImgcodecs {
	GObject parent_instance;
	imgcodecsImgcodecsPrivate * priv;
};

struct _imgcodecsImgcodecsClass {
	GObjectClass parent_class;
};


static gpointer imgcodecs_imgcodecs_parent_class = NULL;

GType imgcodecs_imgcodecs_get_type (void) G_GNUC_CONST;
GType geometry_mat_get_type (void) G_GNUC_CONST;
geometryMat* imgcodecs_imgcodecs_imread (const gchar* filename);
glong imgcodecs_imgcodecs_imread_1 (const gchar* filename);
geometryMat* geometry_mat_new_addr (glong addr);
geometryMat* geometry_mat_construct_addr (GType object_type, glong addr);
imgcodecsImgcodecs* imgcodecs_imgcodecs_new (void);
imgcodecsImgcodecs* imgcodecs_imgcodecs_construct (GType object_type);


geometryMat* imgcodecs_imgcodecs_imread (const gchar* filename) {
	geometryMat* result = NULL;
	geometryMat* retVal = NULL;
	const gchar* _tmp0_;
	glong _tmp1_;
	geometryMat* _tmp2_;
	g_return_val_if_fail (filename != NULL, NULL);
	_tmp0_ = filename;
	_tmp1_ = imgcodecs_imgcodecs_imread_1 (_tmp0_);
	_tmp2_ = geometry_mat_new_addr (_tmp1_);
	retVal = _tmp2_;
	result = retVal;
	return result;
}


imgcodecsImgcodecs* imgcodecs_imgcodecs_construct (GType object_type) {
	imgcodecsImgcodecs * self = NULL;
	self = (imgcodecsImgcodecs*) g_object_new (object_type, NULL);
	return self;
}


imgcodecsImgcodecs* imgcodecs_imgcodecs_new (void) {
	return imgcodecs_imgcodecs_construct (IMGCODECS_TYPE_IMGCODECS);
}


static void imgcodecs_imgcodecs_class_init (imgcodecsImgcodecsClass * klass) {
	imgcodecs_imgcodecs_parent_class = g_type_class_peek_parent (klass);
}


static void imgcodecs_imgcodecs_instance_init (imgcodecsImgcodecs * self) {
}


GType imgcodecs_imgcodecs_get_type (void) {
	static volatile gsize imgcodecs_imgcodecs_type_id__volatile = 0;
	if (g_once_init_enter (&imgcodecs_imgcodecs_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (imgcodecsImgcodecsClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) imgcodecs_imgcodecs_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (imgcodecsImgcodecs), 0, (GInstanceInitFunc) imgcodecs_imgcodecs_instance_init, NULL };
		GType imgcodecs_imgcodecs_type_id;
		imgcodecs_imgcodecs_type_id = g_type_register_static (G_TYPE_OBJECT, "imgcodecsImgcodecs", &g_define_type_info, 0);
		g_once_init_leave (&imgcodecs_imgcodecs_type_id__volatile, imgcodecs_imgcodecs_type_id);
	}
	return imgcodecs_imgcodecs_type_id__volatile;
}



