/* Mat.c generated by valac 0.38.4-dirty, the Vala compiler
 * generated from Mat.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define GEOMETRY_TYPE_MAT (geometry_mat_get_type ())
#define GEOMETRY_MAT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_MAT, geometryMat))
#define GEOMETRY_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_MAT, geometryMatClass))
#define GEOMETRY_IS_MAT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_MAT))
#define GEOMETRY_IS_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_MAT))
#define GEOMETRY_MAT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_MAT, geometryMatClass))

typedef struct _geometryMat geometryMat;
typedef struct _geometryMatClass geometryMatClass;
typedef struct _geometryMatPrivate geometryMatPrivate;
enum  {
	GEOMETRY_MAT_0_PROPERTY,
	GEOMETRY_MAT_NUM_PROPERTIES
};
static GParamSpec* geometry_mat_properties[GEOMETRY_MAT_NUM_PROPERTIES];

struct _geometryMat {
	GObject parent_instance;
	geometryMatPrivate * priv;
	glong nativeObj;
};

struct _geometryMatClass {
	GObjectClass parent_class;
};


static gpointer geometry_mat_parent_class = NULL;

GType geometry_mat_get_type (void) G_GNUC_CONST;
geometryMat* geometry_mat_new (void);
geometryMat* geometry_mat_construct (GType object_type);
glong geometry_mat_n_Mat (void);
geometryMat* geometry_mat_new_addr (glong addr);
geometryMat* geometry_mat_construct_addr (GType object_type, glong addr);
glong geometry_mat_total (geometryMat* self);
glong geometry_mat_n_total (glong nativeObj);
gint geometry_mat_get (geometryMat* self, gint row, gint col, gint* data, int data_length1);
gint geometry_mat_nGetI (glong _self_, gint row, gint col, gint count, gint* vals, int vals_length1);
static void geometry_mat_finalize (GObject * obj);


geometryMat* geometry_mat_construct (GType object_type) {
	geometryMat * self = NULL;
	glong _tmp0_;
	self = (geometryMat*) g_object_new (object_type, NULL);
	_tmp0_ = geometry_mat_n_Mat ();
	self->nativeObj = _tmp0_;
	return self;
}


geometryMat* geometry_mat_new (void) {
	return geometry_mat_construct (GEOMETRY_TYPE_MAT);
}


geometryMat* geometry_mat_construct_addr (GType object_type, glong addr) {
	geometryMat * self = NULL;
	glong _tmp0_;
	self = (geometryMat*) g_object_new (object_type, NULL);
	_tmp0_ = addr;
	self->nativeObj = _tmp0_;
	return self;
}


geometryMat* geometry_mat_new_addr (glong addr) {
	return geometry_mat_construct_addr (GEOMETRY_TYPE_MAT, addr);
}


glong geometry_mat_total (geometryMat* self) {
	glong result = 0L;
	glong retVal = 0L;
	glong _tmp0_;
	glong _tmp1_;
	g_return_val_if_fail (self != NULL, 0L);
	_tmp0_ = self->nativeObj;
	_tmp1_ = geometry_mat_n_total (_tmp0_);
	retVal = _tmp1_;
	result = retVal;
	return result;
}


gint geometry_mat_get (geometryMat* self, gint row, gint col, gint* data, int data_length1) {
	gint result = 0;
	glong _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint* _tmp3_;
	gint _tmp3__length1;
	gint* _tmp4_;
	gint _tmp4__length1;
	gint _tmp5_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->nativeObj;
	_tmp1_ = row;
	_tmp2_ = col;
	_tmp3_ = data;
	_tmp3__length1 = data_length1;
	_tmp4_ = data;
	_tmp4__length1 = data_length1;
	_tmp5_ = geometry_mat_nGetI (_tmp0_, _tmp1_, _tmp2_, _tmp3__length1, _tmp4_, _tmp4__length1);
	result = _tmp5_;
	return result;
}


static void geometry_mat_class_init (geometryMatClass * klass) {
	geometry_mat_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = geometry_mat_finalize;
}


static void geometry_mat_instance_init (geometryMat * self) {
}


static void geometry_mat_finalize (GObject * obj) {
	geometryMat * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEOMETRY_TYPE_MAT, geometryMat);
	G_OBJECT_CLASS (geometry_mat_parent_class)->finalize (obj);
}


GType geometry_mat_get_type (void) {
	static volatile gsize geometry_mat_type_id__volatile = 0;
	if (g_once_init_enter (&geometry_mat_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (geometryMatClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geometry_mat_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (geometryMat), 0, (GInstanceInitFunc) geometry_mat_instance_init, NULL };
		GType geometry_mat_type_id;
		geometry_mat_type_id = g_type_register_static (G_TYPE_OBJECT, "geometryMat", &g_define_type_info, 0);
		g_once_init_leave (&geometry_mat_type_id__volatile, geometry_mat_type_id);
	}
	return geometry_mat_type_id__volatile;
}



