/* MatOfRect.c generated by valac 0.38.4-dirty, the Vala compiler
 * generated from MatOfRect.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define GEOMETRY_TYPE_MAT (geometry_mat_get_type ())
#define GEOMETRY_MAT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_MAT, geometryMat))
#define GEOMETRY_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_MAT, geometryMatClass))
#define GEOMETRY_IS_MAT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_MAT))
#define GEOMETRY_IS_MAT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_MAT))
#define GEOMETRY_MAT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_MAT, geometryMatClass))

typedef struct _geometryMat geometryMat;
typedef struct _geometryMatClass geometryMatClass;
typedef struct _geometryMatPrivate geometryMatPrivate;

#define GEOMETRY_TYPE_MAT_OF_RECT (geometry_mat_of_rect_get_type ())
#define GEOMETRY_MAT_OF_RECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_MAT_OF_RECT, geometryMatOfRect))
#define GEOMETRY_MAT_OF_RECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_MAT_OF_RECT, geometryMatOfRectClass))
#define GEOMETRY_IS_MAT_OF_RECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_MAT_OF_RECT))
#define GEOMETRY_IS_MAT_OF_RECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_MAT_OF_RECT))
#define GEOMETRY_MAT_OF_RECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_MAT_OF_RECT, geometryMatOfRectClass))

typedef struct _geometryMatOfRect geometryMatOfRect;
typedef struct _geometryMatOfRectClass geometryMatOfRectClass;
typedef struct _geometryMatOfRectPrivate geometryMatOfRectPrivate;
enum  {
	GEOMETRY_MAT_OF_RECT_0_PROPERTY,
	GEOMETRY_MAT_OF_RECT_NUM_PROPERTIES
};
static GParamSpec* geometry_mat_of_rect_properties[GEOMETRY_MAT_OF_RECT_NUM_PROPERTIES];

#define GEOMETRY_TYPE_RECTANGLE (geometry_rectangle_get_type ())
#define GEOMETRY_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_RECTANGLE, geometryRectangle))
#define GEOMETRY_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_RECTANGLE, geometryRectangleClass))
#define GEOMETRY_IS_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_RECTANGLE))
#define GEOMETRY_IS_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_RECTANGLE))
#define GEOMETRY_RECTANGLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_RECTANGLE, geometryRectangleClass))

typedef struct _geometryRectangle geometryRectangle;
typedef struct _geometryRectangleClass geometryRectangleClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _geometryMat {
	GObject parent_instance;
	geometryMatPrivate * priv;
	glong nativeObj;
};

struct _geometryMatClass {
	GObjectClass parent_class;
};

struct _geometryMatOfRect {
	geometryMat parent_instance;
	geometryMatOfRectPrivate * priv;
};

struct _geometryMatOfRectClass {
	geometryMatClass parent_class;
};


static gpointer geometry_mat_of_rect_parent_class = NULL;
static gint geometry_mat_of_rect__channels;
static gint geometry_mat_of_rect__channels = 4;

GType geometry_mat_get_type (void) G_GNUC_CONST;
GType geometry_mat_of_rect_get_type (void) G_GNUC_CONST;
geometryMatOfRect* geometry_mat_of_rect_new (void);
geometryMatOfRect* geometry_mat_of_rect_construct (GType object_type);
geometryMat* geometry_mat_new (void);
geometryMat* geometry_mat_construct (GType object_type);
GType geometry_rectangle_get_type (void) G_GNUC_CONST;
geometryRectangle** geometry_mat_of_rect_toArray (geometryMatOfRect* self, int* result_length1);
glong geometry_mat_total (geometryMat* self);
gint geometry_mat_get (geometryMat* self, gint row, gint col, gint* data, int data_length1);
geometryRectangle* geometry_rectangle_new_withBounds (gint x, gint y, gint width, gint height);
geometryRectangle* geometry_rectangle_construct_withBounds (GType object_type, gint x, gint y, gint width, gint height);
static void geometry_mat_of_rect_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


geometryMatOfRect* geometry_mat_of_rect_construct (GType object_type) {
	geometryMatOfRect * self = NULL;
	self = (geometryMatOfRect*) geometry_mat_construct (object_type);
	return self;
}


geometryMatOfRect* geometry_mat_of_rect_new (void) {
	return geometry_mat_of_rect_construct (GEOMETRY_TYPE_MAT_OF_RECT);
}


geometryRectangle** geometry_mat_of_rect_toArray (geometryMatOfRect* self, int* result_length1) {
	geometryRectangle** result = NULL;
	gint num = 0;
	glong _tmp0_;
	geometryRectangle** a = NULL;
	gint _tmp1_;
	geometryRectangle** _tmp2_;
	gint a_length1;
	gint _a_size_;
	gint _tmp3_;
	gint buff[] = NULL;
	gint _tmp5_;
	gint _tmp6_;
	gint* _tmp7_;
	gint buff_length1;
	gint _buff_size_;
	geometryRectangle** _tmp28_;
	gint _tmp28__length1;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = geometry_mat_total ((geometryMat*) self);
	num = (gint) _tmp0_;
	_tmp1_ = num;
	_tmp2_ = g_new0 (geometryRectangle*, _tmp1_ + 1);
	a = _tmp2_;
	a_length1 = _tmp1_;
	_a_size_ = a_length1;
	_tmp3_ = num;
	if (_tmp3_ == 0) {
		geometryRectangle** _tmp4_;
		gint _tmp4__length1;
		_tmp4_ = a;
		_tmp4__length1 = a_length1;
		if (result_length1) {
			*result_length1 = _tmp4__length1;
		}
		result = _tmp4_;
		return result;
	}
	_tmp5_ = num;
	_tmp6_ = geometry_mat_of_rect__channels;
	_tmp7_ = g_new0 (gint, _tmp5_ * _tmp6_);
	buff = _tmp7_;
	buff_length1 = _tmp5_ * _tmp6_;
	_buff_size_ = buff_length1;
	geometry_mat_get ((geometryMat*) self, 0, 0, buff, buff_length1);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp8_ = FALSE;
			_tmp8_ = TRUE;
			while (TRUE) {
				gint _tmp10_;
				gint _tmp11_;
				geometryRectangle** _tmp12_;
				gint _tmp12__length1;
				gint _tmp13_;
				gint _tmp14_;
				gint _tmp15_;
				gint _tmp16_;
				gint _tmp17_;
				gint _tmp18_;
				gint _tmp19_;
				gint _tmp20_;
				gint _tmp21_;
				gint _tmp22_;
				gint _tmp23_;
				gint _tmp24_;
				gint _tmp25_;
				geometryRectangle* _tmp26_;
				geometryRectangle* _tmp27_;
				if (!_tmp8_) {
					gint _tmp9_;
					_tmp9_ = i;
					i = _tmp9_ + 1;
				}
				_tmp8_ = FALSE;
				_tmp10_ = i;
				_tmp11_ = num;
				if (!(_tmp10_ < _tmp11_)) {
					break;
				}
				_tmp12_ = a;
				_tmp12__length1 = a_length1;
				_tmp13_ = i;
				_tmp14_ = i;
				_tmp15_ = geometry_mat_of_rect__channels;
				_tmp16_ = buff[_tmp14_ * _tmp15_];
				_tmp17_ = i;
				_tmp18_ = geometry_mat_of_rect__channels;
				_tmp19_ = buff[(_tmp17_ * _tmp18_) + 1];
				_tmp20_ = i;
				_tmp21_ = geometry_mat_of_rect__channels;
				_tmp22_ = buff[(_tmp20_ * _tmp21_) + 2];
				_tmp23_ = i;
				_tmp24_ = geometry_mat_of_rect__channels;
				_tmp25_ = buff[(_tmp23_ * _tmp24_) + 3];
				_tmp26_ = geometry_rectangle_new_withBounds (_tmp16_, _tmp19_, _tmp22_, _tmp25_);
				_g_object_unref0 (_tmp12_[_tmp13_]);
				_tmp12_[_tmp13_] = _tmp26_;
				_tmp27_ = _tmp12_[_tmp13_];
			}
		}
	}
	_tmp28_ = a;
	_tmp28__length1 = a_length1;
	if (result_length1) {
		*result_length1 = _tmp28__length1;
	}
	result = _tmp28_;
	buff = (g_free (buff), NULL);
	return result;
}


static void geometry_mat_of_rect_class_init (geometryMatOfRectClass * klass) {
	geometry_mat_of_rect_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = geometry_mat_of_rect_finalize;
}


static void geometry_mat_of_rect_instance_init (geometryMatOfRect * self) {
}


static void geometry_mat_of_rect_finalize (GObject * obj) {
	geometryMatOfRect * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEOMETRY_TYPE_MAT_OF_RECT, geometryMatOfRect);
	G_OBJECT_CLASS (geometry_mat_of_rect_parent_class)->finalize (obj);
}


GType geometry_mat_of_rect_get_type (void) {
	static volatile gsize geometry_mat_of_rect_type_id__volatile = 0;
	if (g_once_init_enter (&geometry_mat_of_rect_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (geometryMatOfRectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geometry_mat_of_rect_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (geometryMatOfRect), 0, (GInstanceInitFunc) geometry_mat_of_rect_instance_init, NULL };
		GType geometry_mat_of_rect_type_id;
		geometry_mat_of_rect_type_id = g_type_register_static (GEOMETRY_TYPE_MAT, "geometryMatOfRect", &g_define_type_info, 0);
		g_once_init_leave (&geometry_mat_of_rect_type_id__volatile, geometry_mat_of_rect_type_id);
	}
	return geometry_mat_of_rect_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



