/* Rectangle.c generated by valac 0.38.4-dirty, the Vala compiler
 * generated from Rectangle.vala, do not modify */


#include <glib.h>
#include <glib-object.h>


#define GEOMETRY_TYPE_RECTANGLE (geometry_rectangle_get_type ())
#define GEOMETRY_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEOMETRY_TYPE_RECTANGLE, geometryRectangle))
#define GEOMETRY_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEOMETRY_TYPE_RECTANGLE, geometryRectangleClass))
#define GEOMETRY_IS_RECTANGLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEOMETRY_TYPE_RECTANGLE))
#define GEOMETRY_IS_RECTANGLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEOMETRY_TYPE_RECTANGLE))
#define GEOMETRY_RECTANGLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEOMETRY_TYPE_RECTANGLE, geometryRectangleClass))

typedef struct _geometryRectangle geometryRectangle;
typedef struct _geometryRectangleClass geometryRectangleClass;
typedef struct _geometryRectanglePrivate geometryRectanglePrivate;
enum  {
	GEOMETRY_RECTANGLE_0_PROPERTY,
	GEOMETRY_RECTANGLE_X_PROPERTY,
	GEOMETRY_RECTANGLE_Y_PROPERTY,
	GEOMETRY_RECTANGLE_WIDTH_PROPERTY,
	GEOMETRY_RECTANGLE_HEIGHT_PROPERTY,
	GEOMETRY_RECTANGLE_NUM_PROPERTIES
};
static GParamSpec* geometry_rectangle_properties[GEOMETRY_RECTANGLE_NUM_PROPERTIES];

struct _geometryRectangle {
	GObject parent_instance;
	geometryRectanglePrivate * priv;
};

struct _geometryRectangleClass {
	GObjectClass parent_class;
};

struct _geometryRectanglePrivate {
	gint _x;
	gint _y;
	gint _width;
	gint _height;
};


static gpointer geometry_rectangle_parent_class = NULL;

GType geometry_rectangle_get_type (void) G_GNUC_CONST;
#define GEOMETRY_RECTANGLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), GEOMETRY_TYPE_RECTANGLE, geometryRectanglePrivate))
geometryRectangle* geometry_rectangle_new (void);
geometryRectangle* geometry_rectangle_construct (GType object_type);
geometryRectangle* geometry_rectangle_new_withBounds (gint x, gint y, gint width, gint height);
geometryRectangle* geometry_rectangle_construct_withBounds (GType object_type, gint x, gint y, gint width, gint height);
void geometry_rectangle_set_x (geometryRectangle* self, gint value);
void geometry_rectangle_set_y (geometryRectangle* self, gint value);
void geometry_rectangle_set_width (geometryRectangle* self, gint value);
void geometry_rectangle_set_height (geometryRectangle* self, gint value);
geometryRectangle* geometry_rectangle_new_withRectangle (geometryRectangle* r);
geometryRectangle* geometry_rectangle_construct_withRectangle (GType object_type, geometryRectangle* r);
gint geometry_rectangle_get_x (geometryRectangle* self);
gint geometry_rectangle_get_y (geometryRectangle* self);
gint geometry_rectangle_get_width (geometryRectangle* self);
gint geometry_rectangle_get_height (geometryRectangle* self);
gboolean geometry_rectangle_contains (geometryRectangle* self, geometryRectangle* r);
gboolean geometry_rectangle_containsWithBoundaries (geometryRectangle* self, gint X, gint Y, gint W, gint H);
geometryRectangle* geometry_rectangle_union (geometryRectangle* self, geometryRectangle* r);
static void geometry_rectangle_finalize (GObject * obj);
static void _vala_geometry_rectangle_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_geometry_rectangle_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
void _vala_main (void);


geometryRectangle* geometry_rectangle_construct (GType object_type) {
	geometryRectangle * self = NULL;
	self = (geometryRectangle*) geometry_rectangle_construct_withBounds (object_type, 0, 0, 0, 0);
	return self;
}


geometryRectangle* geometry_rectangle_new (void) {
	return geometry_rectangle_construct (GEOMETRY_TYPE_RECTANGLE);
}


geometryRectangle* geometry_rectangle_construct_withBounds (GType object_type, gint x, gint y, gint width, gint height) {
	geometryRectangle * self = NULL;
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	self = (geometryRectangle*) g_object_new (object_type, NULL);
	_tmp0_ = x;
	geometry_rectangle_set_x (self, _tmp0_);
	_tmp1_ = y;
	geometry_rectangle_set_y (self, _tmp1_);
	_tmp2_ = width;
	geometry_rectangle_set_width (self, _tmp2_);
	_tmp3_ = height;
	geometry_rectangle_set_height (self, _tmp3_);
	return self;
}


geometryRectangle* geometry_rectangle_new_withBounds (gint x, gint y, gint width, gint height) {
	return geometry_rectangle_construct_withBounds (GEOMETRY_TYPE_RECTANGLE, x, y, width, height);
}


geometryRectangle* geometry_rectangle_construct_withRectangle (GType object_type, geometryRectangle* r) {
	geometryRectangle * self = NULL;
	geometryRectangle* _tmp0_;
	gint _tmp1_;
	geometryRectangle* _tmp2_;
	gint _tmp3_;
	geometryRectangle* _tmp4_;
	gint _tmp5_;
	geometryRectangle* _tmp6_;
	gint _tmp7_;
	g_return_val_if_fail (r != NULL, NULL);
	_tmp0_ = r;
	_tmp1_ = _tmp0_->priv->_x;
	_tmp2_ = r;
	_tmp3_ = _tmp2_->priv->_y;
	_tmp4_ = r;
	_tmp5_ = _tmp4_->priv->_width;
	_tmp6_ = r;
	_tmp7_ = _tmp6_->priv->_height;
	self = (geometryRectangle*) geometry_rectangle_construct_withBounds (object_type, _tmp1_, _tmp3_, _tmp5_, _tmp7_);
	return self;
}


geometryRectangle* geometry_rectangle_new_withRectangle (geometryRectangle* r) {
	return geometry_rectangle_construct_withRectangle (GEOMETRY_TYPE_RECTANGLE, r);
}


gboolean geometry_rectangle_contains (geometryRectangle* self, geometryRectangle* r) {
	gboolean result = FALSE;
	geometryRectangle* _tmp0_;
	gint _tmp1_;
	geometryRectangle* _tmp2_;
	gint _tmp3_;
	geometryRectangle* _tmp4_;
	gint _tmp5_;
	geometryRectangle* _tmp6_;
	gint _tmp7_;
	gboolean _tmp8_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (r != NULL, FALSE);
	_tmp0_ = r;
	_tmp1_ = _tmp0_->priv->_x;
	_tmp2_ = r;
	_tmp3_ = _tmp2_->priv->_y;
	_tmp4_ = r;
	_tmp5_ = _tmp4_->priv->_width;
	_tmp6_ = r;
	_tmp7_ = _tmp6_->priv->_height;
	_tmp8_ = geometry_rectangle_containsWithBoundaries (self, _tmp1_, _tmp3_, _tmp5_, _tmp7_);
	result = _tmp8_;
	return result;
}


gboolean geometry_rectangle_containsWithBoundaries (geometryRectangle* self, gint X, gint Y, gint W, gint H) {
	gboolean result = FALSE;
	gint w = 0;
	gint _tmp0_;
	gint h = 0;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint x = 0;
	gint _tmp6_;
	gint y = 0;
	gint _tmp7_;
	gboolean _tmp8_ = FALSE;
	gint _tmp9_;
	gint _tmp10_;
	gint _tmp13_;
	gint _tmp14_;
	gint _tmp15_;
	gint _tmp16_;
	gint _tmp17_;
	gint _tmp18_;
	gint _tmp29_;
	gint _tmp30_;
	gint _tmp31_;
	gint _tmp32_;
	gint _tmp33_;
	gint _tmp34_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_width;
	w = _tmp0_;
	_tmp1_ = self->priv->_height;
	h = _tmp1_;
	_tmp2_ = w;
	_tmp3_ = h;
	_tmp4_ = W;
	_tmp5_ = H;
	if ((((_tmp2_ | _tmp3_) | _tmp4_) | _tmp5_) < 0) {
		result = FALSE;
		return result;
	}
	_tmp6_ = self->priv->_x;
	x = _tmp6_;
	_tmp7_ = self->priv->_y;
	y = _tmp7_;
	_tmp9_ = X;
	_tmp10_ = x;
	if (_tmp9_ < _tmp10_) {
		_tmp8_ = TRUE;
	} else {
		gint _tmp11_;
		gint _tmp12_;
		_tmp11_ = Y;
		_tmp12_ = y;
		_tmp8_ = _tmp11_ < _tmp12_;
	}
	if (_tmp8_) {
		result = FALSE;
		return result;
	}
	_tmp13_ = w;
	_tmp14_ = x;
	w = _tmp13_ + _tmp14_;
	_tmp15_ = W;
	_tmp16_ = X;
	W = _tmp15_ + _tmp16_;
	_tmp17_ = W;
	_tmp18_ = X;
	if (_tmp17_ <= _tmp18_) {
		gboolean _tmp19_ = FALSE;
		gint _tmp20_;
		gint _tmp21_;
		_tmp20_ = w;
		_tmp21_ = x;
		if (_tmp20_ >= _tmp21_) {
			_tmp19_ = TRUE;
		} else {
			gint _tmp22_;
			gint _tmp23_;
			_tmp22_ = W;
			_tmp23_ = w;
			_tmp19_ = _tmp22_ > _tmp23_;
		}
		if (_tmp19_) {
			result = FALSE;
			return result;
		}
	} else {
		gboolean _tmp24_ = FALSE;
		gint _tmp25_;
		gint _tmp26_;
		_tmp25_ = w;
		_tmp26_ = x;
		if (_tmp25_ >= _tmp26_) {
			gint _tmp27_;
			gint _tmp28_;
			_tmp27_ = W;
			_tmp28_ = w;
			_tmp24_ = _tmp27_ > _tmp28_;
		} else {
			_tmp24_ = FALSE;
		}
		if (_tmp24_) {
			result = FALSE;
			return result;
		}
	}
	_tmp29_ = h;
	_tmp30_ = y;
	h = _tmp29_ + _tmp30_;
	_tmp31_ = H;
	_tmp32_ = Y;
	H = _tmp31_ + _tmp32_;
	_tmp33_ = H;
	_tmp34_ = Y;
	if (_tmp33_ <= _tmp34_) {
		gboolean _tmp35_ = FALSE;
		gint _tmp36_;
		gint _tmp37_;
		_tmp36_ = h;
		_tmp37_ = y;
		if (_tmp36_ >= _tmp37_) {
			_tmp35_ = TRUE;
		} else {
			gint _tmp38_;
			gint _tmp39_;
			_tmp38_ = H;
			_tmp39_ = h;
			_tmp35_ = _tmp38_ > _tmp39_;
		}
		if (_tmp35_) {
			result = FALSE;
			return result;
		}
	} else {
		gboolean _tmp40_ = FALSE;
		gint _tmp41_;
		gint _tmp42_;
		_tmp41_ = h;
		_tmp42_ = y;
		if (_tmp41_ >= _tmp42_) {
			gint _tmp43_;
			gint _tmp44_;
			_tmp43_ = H;
			_tmp44_ = h;
			_tmp40_ = _tmp43_ > _tmp44_;
		} else {
			_tmp40_ = FALSE;
		}
		if (_tmp40_) {
			result = FALSE;
			return result;
		}
	}
	result = TRUE;
	return result;
}


geometryRectangle* geometry_rectangle_union (geometryRectangle* self, geometryRectangle* r) {
	geometryRectangle* result = NULL;
	glong tx2 = 0L;
	gint _tmp0_;
	glong ty2 = 0L;
	gint _tmp1_;
	glong _tmp2_;
	glong _tmp3_;
	glong rx2 = 0L;
	geometryRectangle* _tmp6_;
	gint _tmp7_;
	glong ry2 = 0L;
	geometryRectangle* _tmp8_;
	gint _tmp9_;
	glong _tmp10_;
	glong _tmp11_;
	gint tx1 = 0;
	gint _tmp13_;
	gint ty1 = 0;
	gint _tmp14_;
	glong _tmp15_;
	gint _tmp16_;
	glong _tmp17_;
	gint _tmp18_;
	gint rx1 = 0;
	geometryRectangle* _tmp19_;
	gint _tmp20_;
	gint ry1 = 0;
	geometryRectangle* _tmp21_;
	gint _tmp22_;
	glong _tmp23_;
	gint _tmp24_;
	glong _tmp25_;
	gint _tmp26_;
	gint _tmp27_;
	gint _tmp28_;
	gint _tmp30_;
	gint _tmp31_;
	glong _tmp33_;
	glong _tmp34_;
	glong _tmp36_;
	glong _tmp37_;
	glong _tmp39_;
	gint _tmp40_;
	glong _tmp41_;
	gint _tmp42_;
	glong _tmp43_;
	glong _tmp44_;
	gint _tmp45_;
	gint _tmp46_;
	glong _tmp47_;
	glong _tmp48_;
	geometryRectangle* _tmp49_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (r != NULL, NULL);
	_tmp0_ = self->priv->_width;
	tx2 = (glong) _tmp0_;
	_tmp1_ = self->priv->_height;
	ty2 = (glong) _tmp1_;
	_tmp2_ = tx2;
	_tmp3_ = ty2;
	if ((_tmp2_ | _tmp3_) < ((glong) 0)) {
		geometryRectangle* _tmp4_;
		geometryRectangle* _tmp5_;
		_tmp4_ = r;
		_tmp5_ = geometry_rectangle_new_withRectangle (_tmp4_);
		result = _tmp5_;
		return result;
	}
	_tmp6_ = r;
	_tmp7_ = _tmp6_->priv->_width;
	rx2 = (glong) _tmp7_;
	_tmp8_ = r;
	_tmp9_ = _tmp8_->priv->_height;
	ry2 = (glong) _tmp9_;
	_tmp10_ = rx2;
	_tmp11_ = ry2;
	if ((_tmp10_ | _tmp11_) < ((glong) 0)) {
		geometryRectangle* _tmp12_;
		_tmp12_ = geometry_rectangle_new_withRectangle (self);
		result = _tmp12_;
		return result;
	}
	_tmp13_ = self->priv->_x;
	tx1 = _tmp13_;
	_tmp14_ = self->priv->_y;
	ty1 = _tmp14_;
	_tmp15_ = tx2;
	_tmp16_ = tx1;
	tx2 = _tmp15_ + _tmp16_;
	_tmp17_ = ty2;
	_tmp18_ = ty1;
	ty2 = _tmp17_ + _tmp18_;
	_tmp19_ = r;
	_tmp20_ = _tmp19_->priv->_x;
	rx1 = _tmp20_;
	_tmp21_ = r;
	_tmp22_ = _tmp21_->priv->_y;
	ry1 = _tmp22_;
	_tmp23_ = rx2;
	_tmp24_ = rx1;
	rx2 = _tmp23_ + _tmp24_;
	_tmp25_ = ry2;
	_tmp26_ = ry1;
	ry2 = _tmp25_ + _tmp26_;
	_tmp27_ = tx1;
	_tmp28_ = rx1;
	if (_tmp27_ > _tmp28_) {
		gint _tmp29_;
		_tmp29_ = rx1;
		tx1 = _tmp29_;
	}
	_tmp30_ = ty1;
	_tmp31_ = ry1;
	if (_tmp30_ > _tmp31_) {
		gint _tmp32_;
		_tmp32_ = ry1;
		ty1 = _tmp32_;
	}
	_tmp33_ = tx2;
	_tmp34_ = rx2;
	if (_tmp33_ < _tmp34_) {
		glong _tmp35_;
		_tmp35_ = rx2;
		tx2 = _tmp35_;
	}
	_tmp36_ = ty2;
	_tmp37_ = ry2;
	if (_tmp36_ < _tmp37_) {
		glong _tmp38_;
		_tmp38_ = ry2;
		ty2 = _tmp38_;
	}
	_tmp39_ = tx2;
	_tmp40_ = tx1;
	tx2 = _tmp39_ - _tmp40_;
	_tmp41_ = ty2;
	_tmp42_ = ty1;
	ty2 = _tmp41_ - _tmp42_;
	_tmp43_ = tx2;
	if (_tmp43_ > ((glong) G_MAXINT)) {
		tx2 = (glong) G_MAXINT;
	}
	_tmp44_ = ty2;
	if (_tmp44_ > ((glong) G_MAXINT)) {
		ty2 = (glong) G_MAXINT;
	}
	_tmp45_ = tx1;
	_tmp46_ = ty1;
	_tmp47_ = tx2;
	_tmp48_ = ty2;
	_tmp49_ = geometry_rectangle_new_withBounds (_tmp45_, _tmp46_, (gint) _tmp47_, (gint) _tmp48_);
	result = _tmp49_;
	return result;
}


gint geometry_rectangle_get_x (geometryRectangle* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_x;
	result = _tmp0_;
	return result;
}


void geometry_rectangle_set_x (geometryRectangle* self, gint value) {
	g_return_if_fail (self != NULL);
	if (geometry_rectangle_get_x (self) != value) {
		gint _tmp0_;
		_tmp0_ = value;
		self->priv->_x = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, geometry_rectangle_properties[GEOMETRY_RECTANGLE_X_PROPERTY]);
	}
}


gint geometry_rectangle_get_y (geometryRectangle* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_y;
	result = _tmp0_;
	return result;
}


void geometry_rectangle_set_y (geometryRectangle* self, gint value) {
	g_return_if_fail (self != NULL);
	if (geometry_rectangle_get_y (self) != value) {
		gint _tmp0_;
		_tmp0_ = value;
		self->priv->_y = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, geometry_rectangle_properties[GEOMETRY_RECTANGLE_Y_PROPERTY]);
	}
}


gint geometry_rectangle_get_width (geometryRectangle* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


void geometry_rectangle_set_width (geometryRectangle* self, gint value) {
	g_return_if_fail (self != NULL);
	if (geometry_rectangle_get_width (self) != value) {
		gint _tmp0_;
		_tmp0_ = value;
		self->priv->_width = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, geometry_rectangle_properties[GEOMETRY_RECTANGLE_WIDTH_PROPERTY]);
	}
}


gint geometry_rectangle_get_height (geometryRectangle* self) {
	gint result;
	gint _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


void geometry_rectangle_set_height (geometryRectangle* self, gint value) {
	g_return_if_fail (self != NULL);
	if (geometry_rectangle_get_height (self) != value) {
		gint _tmp0_;
		_tmp0_ = value;
		self->priv->_height = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, geometry_rectangle_properties[GEOMETRY_RECTANGLE_HEIGHT_PROPERTY]);
	}
}


static void geometry_rectangle_class_init (geometryRectangleClass * klass) {
	geometry_rectangle_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (geometryRectanglePrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_geometry_rectangle_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_geometry_rectangle_set_property;
	G_OBJECT_CLASS (klass)->finalize = geometry_rectangle_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEOMETRY_RECTANGLE_X_PROPERTY, geometry_rectangle_properties[GEOMETRY_RECTANGLE_X_PROPERTY] = g_param_spec_int ("x", "x", "x", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEOMETRY_RECTANGLE_Y_PROPERTY, geometry_rectangle_properties[GEOMETRY_RECTANGLE_Y_PROPERTY] = g_param_spec_int ("y", "y", "y", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEOMETRY_RECTANGLE_WIDTH_PROPERTY, geometry_rectangle_properties[GEOMETRY_RECTANGLE_WIDTH_PROPERTY] = g_param_spec_int ("width", "width", "width", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEOMETRY_RECTANGLE_HEIGHT_PROPERTY, geometry_rectangle_properties[GEOMETRY_RECTANGLE_HEIGHT_PROPERTY] = g_param_spec_int ("height", "height", "height", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void geometry_rectangle_instance_init (geometryRectangle * self) {
	self->priv = GEOMETRY_RECTANGLE_GET_PRIVATE (self);
	self->priv->_x = 0;
	self->priv->_y = 0;
	self->priv->_width = 0;
	self->priv->_height = 0;
}


static void geometry_rectangle_finalize (GObject * obj) {
	geometryRectangle * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEOMETRY_TYPE_RECTANGLE, geometryRectangle);
	G_OBJECT_CLASS (geometry_rectangle_parent_class)->finalize (obj);
}


/**
     * This class is a partial port of java.awt.Rectangle class.
     */
GType geometry_rectangle_get_type (void) {
	static volatile gsize geometry_rectangle_type_id__volatile = 0;
	if (g_once_init_enter (&geometry_rectangle_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (geometryRectangleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) geometry_rectangle_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (geometryRectangle), 0, (GInstanceInitFunc) geometry_rectangle_instance_init, NULL };
		GType geometry_rectangle_type_id;
		geometry_rectangle_type_id = g_type_register_static (G_TYPE_OBJECT, "geometryRectangle", &g_define_type_info, 0);
		g_once_init_leave (&geometry_rectangle_type_id__volatile, geometry_rectangle_type_id);
	}
	return geometry_rectangle_type_id__volatile;
}


static void _vala_geometry_rectangle_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	geometryRectangle * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEOMETRY_TYPE_RECTANGLE, geometryRectangle);
	switch (property_id) {
		case GEOMETRY_RECTANGLE_X_PROPERTY:
		g_value_set_int (value, geometry_rectangle_get_x (self));
		break;
		case GEOMETRY_RECTANGLE_Y_PROPERTY:
		g_value_set_int (value, geometry_rectangle_get_y (self));
		break;
		case GEOMETRY_RECTANGLE_WIDTH_PROPERTY:
		g_value_set_int (value, geometry_rectangle_get_width (self));
		break;
		case GEOMETRY_RECTANGLE_HEIGHT_PROPERTY:
		g_value_set_int (value, geometry_rectangle_get_height (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_geometry_rectangle_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	geometryRectangle * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEOMETRY_TYPE_RECTANGLE, geometryRectangle);
	switch (property_id) {
		case GEOMETRY_RECTANGLE_X_PROPERTY:
		geometry_rectangle_set_x (self, g_value_get_int (value));
		break;
		case GEOMETRY_RECTANGLE_Y_PROPERTY:
		geometry_rectangle_set_y (self, g_value_get_int (value));
		break;
		case GEOMETRY_RECTANGLE_WIDTH_PROPERTY:
		geometry_rectangle_set_width (self, g_value_get_int (value));
		break;
		case GEOMETRY_RECTANGLE_HEIGHT_PROPERTY:
		geometry_rectangle_set_height (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


void _vala_main (void) {
	return;
}


int main (int argc, char ** argv) {
	_vala_main ();
	return 0;
}



